### ISSUE TITLE
MemoryFileSystem error with master, causes webpack build to fail

### ISSUE THREAD

**Issue by modosc** [ztoben/assets-webpack-plugin#111]
with master when  i run webpack in development mode i get:
```
ERROR in invalid argument
ℹ ｢wdm｣: Failed to compile.
```

i traced it down to this in the debugger:
```
"Error: invalid argument
    at pathToArray (/Users/jon/git/swoop/node_modules/memory-fs/lib/MemoryFileSystem.js:44:10)
    at MemoryFileSystem.readFileSync (/Users/jon/git/swoop/node_modules/memory-fs/lib/MemoryFileSystem.js:103:13)
    at MemoryFileSystem.(anonymous function) [as readFile] (/Users/jon/git/swoop/node_modules/memory-fs/lib/MemoryFileSystem.js:300:34)
    at /Users/jon/git/swoop/node_modules/assets-webpack-plugin/dist/lib/output/createOutputWriter.js:48:10
    at Immediate._onImmediate (/Users/jon/git/swoop/node_modules/memory-fs/lib/MemoryFileSystem.js:288:4)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```
the error seems to come from `./` being passed in as the default path:
```
// memory-fs/lib/MemoryFileSystem.js:44:10
function pathToArray(path) {
	path = normalize(path);
	var nix = /^\//.test(path);
	if(!nix) {
		if(!/^[A-Za-z]:/.test(path)) {
			throw new MemoryFileSystemError(errors.code.EINVAL, path);
		}

```
 if i do:
```
new AssetsPlugin({ path: __dirname })
```
then the error doesn't happen (file isn't written to the fs though but that's a separate issue).

**Comment by ztoben** [comment]
This is related to some work being done in #92. When I have time to take a look at it I'll let you know.

**Comment by modosc** [comment]
no worries, i have a working version with the chunk fix from #109.

**Comment by ztoben** [comment]
@modosc, could you try 3.8.4-alpha.1 and let me know if this is working for you now? Thanks!

**Comment by ztoben** [comment]
@modosc, this should be fixed in master and I'll be doing a new release soon(ish) so you'll be able to pull it in from npm.

Let me know if master isn't working for you. Thanks!
