### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by kavinio** [ztoben/assets-webpack-plugin#119]
webpack build fails with the below stack after upgrading to version 3.9.1. Works fine with version 3.8.4

```
Fatal error: Path must be a string. Received undefined
TypeError: Path must be a string. Received undefined
  at assertPath (path.js:7:11)
  at Object.resolve (path.js:1152:7)
  at NodeOutputFileSystem.mkdirP (/Users/ka01733/myproject/node_modules/mkdirp/index.js:25:14)
  at writeOutput (/Users/ka01733/myproject/node_modules/assets-webpack-plugin/dist/lib/output/createOutputWriter.js:39:8)
  at AssetsWebpackPlugin.queuedWriter (/Users/ka01733/myproject/node_modules/assets-webpack-plugin/dist/lib/output/createQueuedWriter.js:31:7)
  at afterEmit (/Users/ka01733/myproject/node_modules/assets-webpack-plugin/dist/index.js:118:12)
  at AsyncSeriesHook.eval [as callAsync] (<anonymous>:7:1)
  at AsyncSeriesHook.lazyCompileHook [as _callAsync] (/Users/ka01733/myproject/node_modules/tapable/lib/Hook.js:35:21)
  at asyncLib.forEach.err (/Users/ka01733/myproject/node_modules/webpack/lib/Compiler.js:355:27)
  at done (/Users/ka01733/myproject/node_modules/neo-async/async.js:2854:11)
  at /Users/ka01733/myproject/node_modules/neo-async/async.js:2805:7
  at /Users/ka01733/myproject/node_modules/graceful-fs/graceful-fs.js:43:10
  at FSReqWrap.oncomplete (fs.js:123:15)
```
node version = v6.14.2

**Comment by ztoben** [comment]
Could you post your webpack config please?

**Comment by kavinio** [comment]
webpack.common.js
```
const _ = require('lodash');
const path = require('path');
const config = require('../config');

/*
 * Webpack Plugins
 */
const webpack = require('webpack');
const ProvidePlugin = webpack.ProvidePlugin;
const DefinePlugin = webpack.DefinePlugin;
const AssetsPlugin = require('assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');

module.exports = {
  webpack: {
    /*
     * Entrypoints, js and scss
     *
     * See: https://webpack.github.io/docs/multiple-entry-points.html
     */
    entry: {
      base: path.join(__dirname, '../..', config.paths.client, 'js/base.js')
    },

    /*
     * A SourceMap without column-mappings
     *
     * See: https://webpack.github.io/docs/configuration.html#devtool
     */
    devtool: 'source-map',

    /*
     * Output files, goes to build/static/js/bundle.js and build/static/css/style.css
     *
     * See: https://webpack.github.io/docs/configuration.html#output
     */
    output: {
      path: path.join(__dirname, '../..', config.paths.buildStatic)
    },

    optimization: {
      runtimeChunk: {
        name: 'manifest',
      }
    },


    plugins: [
  		new DefinePlugin({
  			'process.env.APP_ENV': JSON.stringify('BROWSER'),
        'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV || 'development'),
  		}),

      /*
       * Automatically load jQuery, using '$' and 'jQuery' as identifiers
       *
       * See: https://webpack.github.io/docs/list-of-plugins.html#provideplugin
       */
      new ProvidePlugin({
        $: 'jquery',
        jQuery: 'jquery'
      }),

      /*
       * Create a JSON file mapping of asset file names to hashed asset file names
       *
       * See: https://github.com/kossnocorp/assets-webpack-plugin
       */
      new AssetsPlugin({
        filename: path.join(config.paths.build, 'assetMappings.json')
      }),

      /*
       * Copy static images to the build folder
       *
       * See: https://www.npmjs.com/package/copy-webpack-plugin
       */
      new CopyWebpackPlugin([
        {
          context: path.join(config.paths.client, 'images'),
          from: '**',
          to: path.join(__dirname, '../..', config.paths.buildStatic, 'images')
        },
        {
          context: config.paths.views,
          from: '**',
          to: path.join(__dirname, '../..', config.paths.build, 'views')
        }
      ]),

      /*
       * Extract the css from the bundle into a separate css output file, so css is no
       * longer inline in the javascript.
       */
      new MiniCssExtractPlugin({
        filename:'[name]-[chunkhash:8].css'
      })

    ],

    module: {
      /*
       * Extracts SourceMaps for source files
       *
       * See: https://github.com/webpack/source-map-loader
       */
      rules: [
        {
          enforce: 'pre',
          test: /\.js$/,
          loader: 'source-map-loader'
        },



        /*
         * Babel loader
         *
         * See: https://github.com/babel/babel-loader
         */
        {
          test: /\.js$/,
          exclude: /(node_modules|bower_components|automation_detect.obfuscated.js|request_signature.obfuscated.js)/,
          loader: 'babel-loader',
          query: {
            presets: ['es2015']
          }
        },


        /*
         * Css loader
         *
         * See: https://github.com/webpack/css-loader
         */
        {
          test: /\.css$/,
          use:[{
            loader: MiniCssExtractPlugin.loader,
          },'style-loader', 'css-loader']
        },

        /*
         * File loader
         *
         * See: https://github.com/webpack/url-loader
         */
        {
          test: /\.png$/,
          loader: 'url-loader',
          query: {
            mimetype: 'image/png'
          }
        }
      ]
    }
  }
};
```

webpack.dev.js
```
const config = require('../config');

const webpackMerge = require('webpack-merge'); // used to merge webpack configs
const commonConfig = require('./webpack.common.js'); // the settings that are common to prod and dev

/**
 * Webpack configuration
 *
 * See: https://webpack.github.io/docs/configuration.html#cli
 */
module.exports = webpackMerge(commonConfig, {
  webpack: {

    /**
     * Developer tool to enhance debugging
     *
     * See: http://webpack.github.io/docs/configuration.html#devtool
     * See: https://github.com/webpack/docs/wiki/build-performance#sourcemaps
     */
    devtool: 'source-map',

    mode: 'development',

    output: {
      /**
       * Specifies the name of each output file on disk.
       * IMPORTANT: You must not specify an absolute path here!
       *
       * See: http://webpack.github.io/docs/configuration.html#output-filename
       */
      filename: '[name].js',

      /**
       * The filename of the SourceMaps for the JavaScript files.
       * They are inside the output.path directory.
       *
       * See: http://webpack.github.io/docs/configuration.html#output-sourcemapfilename
       */
      sourceMapFilename: '[name].map',

      /** The filename of non-entry chunks as relative path
       * inside the output.path directory.
       *
       * See: http://webpack.github.io/docs/configuration.html#output-chunkfilename
       */
      chunkFilename: '[id].chunk.js'
    },

    /**
     * Webpack Development Server configuration
     * Description: The webpack-dev-server is a little node.js Express server.
     * The server emits information about the compilation state to the client,
     * which reacts to those events.
     *
     * See: https://webpack.github.io/docs/webpack-dev-server.html
     */
    devServer: {
      port: 8081,
      host: 'localhost',
      historyApiFallback: true,
      watchOptions: {
        aggregateTimeout: 300,
        poll: 1000
      },
      outputPath: config.paths.buildStatic
    },
  }
});
```

**Comment by ztoben** [comment]
Try this: 

```js
new AssetsPlugin({
  filename: 'assetMappings.json',
  path: path.resolve(config.paths.build)
})
```

**Comment by kavinio** [comment]
Apparently, this worked:
```
new AssetsPlugin({
  filename: 'assetMappings.json',
  path: '.'
})
```
Thanks!
