### ISSUE TITLE
Cannot read property 'integrity' of undefined

### ISSUE THREAD

**Issue by ztoben** [ztoben/assets-webpack-plugin#169]
**Describe the bug**
As reported in https://github.com/symfony/webpack-encore/issues/531, there is an error when trying to access the `integrity` field of an undefined compilation asset.

```
Uncaught TypeError: Cannot read property 'integrity' of undefined
  at node_modules/assets-webpack-plugin/dist/index.js:97:55
  at Array.reduce (<anonymous>)
  at node_modules/assets-webpack-plugin/dist/index.js:87:30
  at Array.reduce (<anonymous>)
  at afterEmit (node_modules/assets-webpack-plugin/dist/index.js:74:27)
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:7:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules/tapable/lib/Hook.js:154:20)
  at asyncLib.forEachLimit.err (node_modules/webpack/lib/Compiler.js:432:27)
  at node_modules/neo-async/async.js:2813:7
  at done (node_modules/neo-async/async.js:3521:9)
  at node_modules/graceful-fs/graceful-fs.js:45:10
  at FSReqWrap.oncomplete (fs.js:141:20)
```

**Expected behavior**
Clients not using integrity shouldn't be affected by its functionality.

**Comment by weaverryan** [comment]
Thank you for this! So fast!
