### ISSUE TITLE
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape

### ISSUE THREAD

**Issue by Aralhi** [ztoben/assets-webpack-plugin#233]
**Describe the bug**
Webpack build failed with the error.

**To Reproduce**
/Users/uc/Documents/intlnews/node_modules/_camelcase@6.0.0@camelcase/index.js:69
                .replace(/[_.\- ]+([\p{Alpha}\p{N}_]|$)/gu, (_, p1) => p1.toLocaleUpperCase())
  ^
SyntaxError: Invalid regular expression: /[_.\- ]+([\p{Alpha}\p{N}_]|$)/: Invalid escape
    at camelCase (/Users/uc/Documents/intlnews/node_modules/_camelcase@6.0.0@camelcase/index.js:69:3)
    at getAssetKind (/Users/uc/Documents/intlnews/node_modules/_assets-webpack-plugin@3.10.0@assets-webpack-plugin/dist/lib/getAssetKind.js:9:10)
    at /Users/uc/Documents/intlnews/node_modules/_assets-webpack-plugin@3.10.0@assets-webpack-plugin/dist/index.js:93:26
    at Array.reduce (<anonymous>)
    at /Users/uc/Documents/intlnews/node_modules/_assets-webpack-plugin@3.10.0@assets-webpack-plugin/dist/index.js:87:30
    at Array.reduce (<anonymous>)
    at Compiler.afterEmit (/Users/uc/Documents/intlnews/node_modules/_assets-webpack-plugin@3.10.0@assets-webpack-plugin/dist/index.js:74:27)
    at Compiler.applyPluginsAsyncSeries1 (/Users/uc/Documents/intlnews/node_modules/_tapable@0.2.9@tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/uc/Documents/intlnews/node_modules/_webpack@3.12.0@webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/Users/uc/Documents/intlnews/node_modules/_webpack@3.12.0@webpack/lib/Compiler.js:350:15)
    at /Users/uc/Documents/intlnews/node_modules/_async@2.6.3@async/dist/async.js:473:16
    at iteratorCallback (/Users/uc/Documents/intlnews/node_modules/_async@2.6.3@async/dist/async.js:1064:13)
    at /Users/uc/Documents/intlnews/node_modules/_async@2.6.3@async/dist/async.js:969:16
    at /Users/uc/Documents/intlnews/node_modules/_graceful-fs@4.2.4@graceful-fs/graceful-fs.js:61:14
    at FSReqWrap.oncomplete (fs.js:135:15)

**Expected behavior**
it works fine when i build by assets-webpack-plugin@3.9.12, and 3.10.0 cause this problem.

**Webpack config**
``` 
const AssetsPlugin = require('assets-webpack-plugin')
return {
  plugins: [
    new AssetsPlugin({
        filename: 'assetsmap.json',
        path: assetMapPath
      })
  ]
} 
```

**Desktop (please complete the following information):**
 - OS: MAC
 - Node version: v8.9.0
 - Plugin version: assets-webpack-plugin@3.10.0

**Comment by ztoben** [comment]
So the issue is that you're using a version of node that is lower than the required version. I didn't realize that this wouldn't error without some more configuration in an `.npmrc` file in the project.

Is there any reason you are still on v8.9.0? I can maybe reconsider my decision to bump the minimum version supported if there is a good enough reason.

**Comment by Herz3h** [comment]
I had same issue today. The reason I still use v8 is so that `webpack-dev-server` serves content over HTTP/2 as the protocol is not supported on v10+ @ztoben

**Comment by ztoben** [comment]
@Herz3h node 8 lts reached its end of life in December 2019. I don't have any plans on supporting it going forward, sorry. If you're okay with using an older version `3.9.12` should suit your needs.

**Comment by Herz3h** [comment]
Thank you for the suggestion. What I did is use only caching in production mode and not dev. That way I can still run `webpack-dev-server` with node 8 and have HTTP/2 👍
