### ISSUE TITLE
keepInMemory results in a crash when not running dev-server

### ISSUE THREAD

**Issue by SPWizard01** [ztoben/assets-webpack-plugin#268]
**Describe the bug**
when keepInMemory is set to true, **webpack 5.0.0-rc.4** crashes with the following exception:
```
C:\someproject\node_modules\assets-webpack-plugin\dist\lib\output\createOutputWriter.js:86
    options.keepInMemory ? localFs.mkdirp(options.path, mkdirpCallback) : mkdirp(options.path).then(mkdirpCallback).catch(handleMkdirpError);
                                   ^
TypeError: localFs.mkdirp is not a function
    at writeOutput (C:\someproject\node_modules\assets-webpack-plugin\dist\lib\output\createOutputWriter.js:86:36)
    at AssetsWebpackPlugin.queuedWriter [as writer] (C:\someproject\node_modules\assets-webpack-plugin\dist\lib\output\createQueuedWriter.js:31:7)      
    at afterEmit (C:\someproject\node_modules\assets-webpack-plugin\dist\index.js:165:12)
    at Hook.eval [as callAsync] (eval at create (C:\someproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:5:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\someproject\node_modules\webpack\node_modules\tapable\lib\Hook.js:18:14)
    at C:\someproject\node_modules\webpack\lib\Compiler.js:727:27
    at C:\someproject\node_modules\neo-async\async.js:2818:7
    at done (C:\someproject\node_modules\neo-async\async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (C:\someproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at C:\someproject\node_modules\webpack\lib\Compiler.js:611:33
    at C:\someproject\node_modules\graceful-fs\graceful-fs.js:144:16
    at C:\someproject\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:155:23)
```

**To Reproduce**
have this in your configuration:
```
    new AssetsPlugin({
      path: resolve(__dirname, "./dist"),
      entrypoints: true,
      filename: "webpack.assets",
      keepInMemory: true,
    })
```
and rund webpack (not dev-server)

**Expected behavior**
webpack produces output

**Webpack Config**
default configuration will suffice

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Node version: v12.18.0
 - Plugin version: 5.1.2

**Additional context**
webpack 4 works as expected

**Comment by ztoben** [comment]
Thanks for the report. I haven't started looking at updating for webpack 5 at all and am quite busy at the moment so this may take a little while to get figured out.

**Comment by ztoben** [comment]
I've started working on the webpack 5 changes, if you try the `6.0.0-alpha.2` release this may be working for you now. Please let me know if there are additional errors, thanks!

**Comment by SPWizard01** [comment]
i think you forgot to add memfs as dependency (or something is wrong on my side) :)
`[webpack-cli] Error: Cannot find module 'memfs'`

installing it manually solves the issue

also having keepInMemory true result in no output at all in dist now :)

**Comment by ztoben** [comment]
@SPWizard01 I have a new release `6.0.0-alpha.3`, since you seem to be one of the first to try running webpack 5 with my plugin would you mind seeing if you run into any other issues? I no longer rely on `memfs` so that shouldn't be an issue any more.

**Comment by SPWizard01** [comment]
@ztoben  yep this seems to have been resolved and keepInMemory: true also result in proper output when **not** running dev-server with **webpack 5.0.0**

However this seems to be broken with **5.1.0** `keepInMemory: true` and webpack-dev-server **running** 🤣 
```
i ｢wdm｣: wait until bundle finished: /webpack.assets
× ｢wdm｣: assets by chunk 2.77 MiB (auxiliary name: somechunk)
```
...
```
ERROR in no such file or directory

webpack 5.1.0 compiled with 2 errors in 181143 ms
i ｢wdm｣: Failed to compile.

C:\someproject\node_modules\webpack\lib\logging\Logger.js:123
                        throw new Error(`No such label '${label}' for WebpackLogger.timeEnd()`);
         		^
Error: No such label 'emitAssets' for WebpackLogger.timeEnd()
    at WebpackLogger.timeEnd (C:\someproject\node_modules\webpack\lib\logging\Logger.js:123:10)
    at C:\someproject\node_modules\webpack\lib\Watching.js:81:15
    at C:\someproject\node_modules\webpack\lib\Compiler.js:733:14
    at Hook.eval [as callAsync] (eval at create (C:\someproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at C:\someproject\node_modules\webpack\lib\Compiler.js:730:27
    at C:\someproject\node_modules\neo-async\async.js:2818:7
    at done (C:\someproject\node_modules\neo-async\async.js:3522:9)
    at Hook.eval [as callAsync] (eval at create (C:\someproject\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)
    at C:\someproject\node_modules\webpack\lib\Compiler.js:614:33
    at MemoryFileSystem.writeFile (C:\someproject\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)    
    at doWrite (C:\someproject\node_modules\webpack\lib\Compiler.js:601:30)
    at processMissingFile (C:\someproject\node_modules\webpack\lib\Compiler.js:677:15)
    at C:\someproject\node_modules\webpack\lib\Compiler.js:711:10
    at Immediate.<anonymous> (C:\someproject\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:282:5)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
```

**Comment by ztoben** [comment]
So it works for me on webpack-cli@4.x running `webpack serve`, but I do see the same error as you running in webpack-cli@3.x running `webpack-dev-server`. Wondering if this is an issue on their end or my end. I'll keep looking into it.

**Comment by SPWizard01** [comment]
does not work for me with webpack-cli@4, same error, but i start webpack-dev-server through ts-node (dont know if it can have an impact):
````
import devServer from "webpack-dev-server";
import webpack from "webpack";
import config from "./webpack.dev";
import { merge } from "webpack-merge";
import { resolve } from "path";
import { readFileSync } from "fs";
const resultConfig = merge(config, {
  output: {
    filename: "js/[name].js?[contenthash]",
    chunkFilename: "js/[name].js?[contenthash]",
  },
  target: "web",
});

const cmp = webpack(resultConfig);
const watcher = new devServer(cmp, {
  https: {
    pfx: readFileSync("./somepfx.pfx"),
    passphrase: "somepwd",
  },
  headers: {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "*",
  },
  hot: true,
  contentBase: resolve(__dirname, "dist"),
  publicPath: "/",
  port: 12345,
});

watcher.listen(12345, "localhost");
````
and then i do something like:
`cross-env TS_NODE_PROJECT=\"tsconfig.webpack.json\" ts-node ./webpack.server.ts`

**Comment by ztoben** [comment]
Yeah, you'll need to serve using `@webpack-cli/serve` rather than `webpack-dev-server`. Based on the next webpack 5 bug you submitted I'm guessing you got it working.

**Comment by SPWizard01** [comment]
i switched to `keepInMemory: false` to make it work.
Also for now, i turned off the plugin because i cannot use HMR when it is present (the next bug).
