### ISSUE TITLE
"5.1.2" is OK, "6.0.1" is wrong!!!Error: No such label 'emitAssets' for WebpackLogger.timeEnd()

### ISSUE THREAD

**Issue by LP1994** [ztoben/assets-webpack-plugin#278]
**Describe the bug**
After my gradual verification, it is the problem of this plug-in: assets-webpack-plugin v6.0.1!!!
If "assets-webpack-plugin" is rolled back to "5.1.2", there will be no error!!!

[webpack-cli] Uncaught exception: Error: No such label 'emitAssets' for WebpackLogger.timeEnd()
[webpack-cli] Error: No such label 'emitAssets' for WebpackLogger.timeEnd()
at WebpackLogger.timeEnd (G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\logging\Logger.js:123:10)
at G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Watching.js:81:15
at G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:733:14
at Hook.eval [as callAsync] (eval at create (G:\SNWS\sn-micro-front-web-project-template\node_modules\tapable\lib\HookCodeFactory.js:33:10), :26:1)
at G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:730:27
at G:\SNWS\sn-micro-front-web-project-template\node_modules\neo-async\async.js:2818:7
at done (G:\SNWS\sn-micro-front-web-project-template\node_modules\neo-async\async.js:3522:9)
at Hook.eval [as callAsync] (eval at create (G:\SNWS\sn-micro-front-web-project-template\node_modules\tapable\lib\HookCodeFactory.js:33:10), :6:1)
at G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:614:33
at MemoryFileSystem.writeFile (G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
at doWrite (G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:601:30)
at processMissingFile (G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:677:15)
at G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack\lib\Compiler.js:711:10
at Immediate. (G:\SNWS\sn-micro-front-web-project-template\node_modules\webpack-dev-middleware\node_modules\memory-fs\lib\MemoryFileSystem.js:282:5)
![image](https://user-images.githubusercontent.com/12012671/96215529-d8269500-0fb0-11eb-8257-b21a21d8c813.png)

**To Reproduce**
After my gradual verification, it is the problem of this plug-in: assets-webpack-plugin v6.0.1.
If "assets-webpack-plugin" is rolled back to "5.1.2", there will be no error.

**Expected behavior**
It can run without error.

**Webpack Config**
no

**Desktop (please complete the following information):**
webpack version: v5.1.2
Node.js version: v14.14.0
Operating System: Windows 10
npm: v6.14.8
webpack-cli: v4.0.0
assets-webpack-plugin:  v6.0.1

**Additional context**
no

**Comment by LP1994** [comment]
There is no error when the value of option "keepinmemory" is Boolean "false".

**Comment by LP1994** [comment]
An error occurred when the value of option 'keepinmemory' is Boolean 'true'.

**Comment by LP1994** [comment]
Whether it's development mode or production mode.

**Comment by LP1994** [comment]
However, the differences mentioned above only appear in the development mode.

**Comment by ztoben** [comment]
Okay, I can replicate so I'll see if I can figure out what's going on. Thanks!

**Comment by ztoben** [comment]
@LP1994, could you try release `6.0.3` and let me know if that works for you?

**Comment by LP1994** [comment]
> @LP1994, could you try release `6.0.3` and let me know if that works for you?

I'm sorry, I've just heard from you now. I'll try it now.

**Comment by LP1994** [comment]
> @LP1994, could you try release `6.0.3` and let me know if that works for you?

Yes, the "6.0.3" version solves the problems mentioned above. Looking forward to its official release. Thank you very much for your timely repair.
This question will be closed later.
